config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/contact',  to: 'static_pages#contact'
  get  '/help',     to: 'static_pages#help'
  get  '/signup',   to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :presentations
  resources :sliders
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slider.rb
class Slider < ApplicationRecord
  # belongs_to :presentation
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  before_action :set_slider, only: [:show, :edit, :update, :destroy]

  # GET /sliders
  # GET /sliders.json
  def index
    @sliders = Slider.all
  end

  # GET /sliders/1
  # GET /sliders/1.json
  def show
  end

  # GET /sliders/new
  def new
    @slider = Slider.new
  end

  # GET /sliders/1/edit
  def edit
  end

  # POST /sliders
  # POST /sliders.json
  def create
    @slider = Slider.new(slider_params)

    respond_to do |format|
      if @slider.save
        format.html { redirect_to @slider, notice: 'Slider was successfully created.' }
        format.json { render :show, status: :created, location: @slider }
      else
        format.html { render :new }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sliders/1
  # PATCH/PUT /sliders/1.json
  def update
    respond_to do |format|
      if @slider.update(slider_params)
        format.html { redirect_to @slider, notice: 'Slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @slider }
      else
        format.html { render :edit }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sliders/1
  # DELETE /sliders/1.json
  def destroy
    @slider.destroy
    respond_to do |format|
      format.html { redirect_to sliders_url, notice: 'Slider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Slider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_params
      params.require(:slider).permit(:content)
    end
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/views/sliders/_form.html.erb
<%= form_with(model: slider, local: true) do |form| %>
  <% if slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slider.errors.count, "error") %> prohibited this slider from being saved:</h2>

      <ul>
      <% slider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :slider_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sliders/edit.html.erb
<h1>Editing Slider</h1>

<%= render 'form', slider: @slider %>

<%= link_to 'Show', @slider %> |
<%= link_to 'Back', sliders_path %>

app/views/sliders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sliders</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sliders.each do |slider| %>
      <tr>
        <td><%= slider.content %></td>
        <td><%= link_to 'Show', slider %></td>
        <td><%= link_to 'Edit', edit_slider_path(slider) %></td>
        <td><%= link_to 'Destroy', slider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slider', new_slider_path %>

app/views/sliders/new.html.erb
<h1>New Slider</h1>

<%= render 'form', slider: @slider %>

<%= link_to 'Back', sliders_path %>

app/views/sliders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @slider.content %>
</p>

<%= link_to 'Edit', edit_slider_path(@slider) %> |
<%= link_to 'Back', sliders_path %>