config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/contact',  to: 'static_pages#contact'
  get  '/help',     to: 'static_pages#help'
  get  '/signup',   to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :presentations
  resources :sliders
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  # belongs_to :user
  has_many :sliders
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:title, :user_id, :slider_id)
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= form_with(model: presentation, local: true) do |form| %>
  <% if presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% presentation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :presentation_title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :presentation_user_id %>
  </div>

  <div class="field">
    <%= form.label :slider_id %>
    <%= form.number_field :slider_id, id: :presentation_slider_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presentations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Slider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= presentation.title %></td>
        <td><%= presentation.user_id %></td>
        <td><%= presentation.slider_id %></td>
        <td><%= link_to 'Show', presentation %></td>
        <td><%= link_to 'Edit', edit_presentation_path(presentation) %></td>
        <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presentation', new_presentation_path %>

app/views/presentations/new.html.erb
<h1>New Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @presentation.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @presentation.user_id %>
</p>

<p>
  <strong>Slider:</strong>
  <%= @presentation.slider_id %>
</p>

<%= link_to 'Edit', edit_presentation_path(@presentation) %> |
<%= link_to 'Back', presentations_path %>